### ISSUE TITLE
Zastavit HV při minimalizaci okna

### ISSUE THREAD

**Issue by kudlav** [kmzbrnoI/Jerry#5]
Při řízení se mi podařilo omylem minimalizovat okno Jerry a vlak pokračoval v jízdě.

Je to otázka, zda-li je to špatně. Osobně minimalizaci Jerryho nikdy neprovádím a tak bych považoval minimalizaci za důvod zastavit hnací vozidla.

Změnu okna v popředí (překliknutí na reliéf) bych ponechal beze změny - bez zastavení.

**Comment by malinajan** [comment]
Souhlasím. Minimalizace = zastavit všechna ručně řízená HV.
