### ISSUE TITLE
Nejde ovládat funkci F28

### ISSUE THREAD

**Issue by petrilakm** [kmzbrnoI/Jerry#9]
V regulátoru jsou dostupné pouze funkce F0-F27.

Problematický kod je zde:
https://github.com/kmzbrnoI/Jerry/blob/b6a80efd9b7eb275ef0dce0e0f27de41ef63b7ab/src/Regulator.pas#L609C1-L609C26

**Comment by malinajan** [comment]
Primární důvod je, že se další checkbox prostě do okýnka nevejde. Nechtěl jsem okénko zvětšovat, aby zůstalo kompaktní, moc nepřekrývalo reliéf a dalo se jich dát na obrazovku hezky více. Je ovládàní F28 potřebné?

**Comment by petrilakm** [comment]
Ano, potřebné je. F28 je funkce jako každá další. MS ji používá u všech loko.

Nejdou checkboxy k sobě nějak víc natlačít? Můžu zkusit s tím něco udělat.

**Comment by malinajan** [comment]
Moc nejdou. Můžeš s tím zkusit něco udělat.
